### ISSUE TITLE
mapbox example

### ISSUE THREAD

**Issue by tomtom99** [pengrad/MapScaleView#10]
Could add a mapbox example to this somewhere? I can't figure out how to get it to work.

Thanks

**Comment by pengrad** [comment]
Mapbox API is same Google Maps, you just get `CameraPosition` and update zoom with latitude on `MapScaleView`

```java
CameraPosition cameraPosition = map.getCameraPosition();
scaleView.update(cameraPosition.zoom, cameraPosition.target.latitude);
```
