### ISSUE TITLE
Needs a little bit of margin at top.

### ISSUE THREAD

**Issue by kptlronyttcna** [pengrad/MapScaleView#13]
![screenshot](https://user-images.githubusercontent.com/15993774/44664558-db551480-aa28-11e8-92d4-b71b4e918203.png)

Stroke at top is not visible.

**Comment by pengrad** [comment]
Thanks for reporting!
Did you set custom stroke width? What is it? (I just want to reproduce)

**Comment by kptlronyttcna** [comment]
Wow. That was fast.

No I did not set custom stroke. Tested it on two devices and also the emulator.

**Comment by pengrad** [comment]
Ok, will try to fix asap :)

**Comment by pengrad** [comment]
Released in `com.github.pengrad:mapscaleview:1.4.1`
Thank you!
