### ISSUE TITLE
Another incorrect scaling?

### ISSUE THREAD

**Issue by kptlronyttcna** [pengrad/MapScaleView#14]
[This is from google maps](https://imgur.com/a/PsxRGF8)
[This is from Mapbox showing Google tiles and MapScaleView](https://imgur.com/a/t8Z9HYa)
[This is from Mapbox showing Mapbox tiles and MapScaleView
](https://imgur.com/a/JEtHvHB)
According to MapScaleView that length should be almost 4000ft.

**Comment by pengrad** [comment]
Thanks for reporting!
Is it for mapbox only, or same for Google Maps sdk?

**Comment by kptlronyttcna** [comment]
I don't know about google maps. Don't have API key.

**Comment by pengrad** [comment]
It's correct with google maps sdk
![image](https://user-images.githubusercontent.com/2172170/48311221-09c9a100-e5cf-11e8-9b3d-8043544360af.png)

Could you double check zoom level and latitude that you pass to `mapScaleView.update`?
I will try to make mapbox sample

**Comment by pengrad** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/9417

**Comment by shikhaverma2009** [comment]
hi, 

I used this map scale control ... it shows the same number for mile and kms. 
![testfile](https://user-images.githubusercontent.com/46456001/50785313-3b34b500-127e-11e9-9634-bd2abcf672d6.png)

can you explain why??

**Comment by kptlronyttcna** [comment]
> hi,
> 
> I used this map scale control ... it shows the same number for mile and kms.
> ![testfile](https://user-images.githubusercontent.com/46456001/50785313-3b34b500-127e-11e9-9634-bd2abcf672d6.png)
> 
> can you explain why??

Same numbers, different lengths (look the the small vertical bars, the top one is for kms and the bottom one is for miles)

**Comment by shikhaverma2009** [comment]
Hi !

These value matches with Google maps scale bar but doesn't match with
arcgis maps . I am using scale bar for arcgis. I am not sure weather these
scale bar value is correct or not. Is there any way I can figure this out.


Thanks,
Shikha
