### ISSUE TITLE
Add centimeters

### ISSUE THREAD

**Issue by kptlronyttcna** [pengrad/MapScaleView#15]
Miles scale goes down to 1 foot while meters scale goes down to 1 meter.
1 foot = 0.3 meters
Therefore the meters scale should go down to 30 centimeters.

**Comment by pengrad** [comment]
Is there maps with such zoom level?
Maybe just limit feet by 2?

**Comment by kptlronyttcna** [comment]
We have maps with such zoom levels. Devices such as those from Trimble have sub-meter accuracy (around 15cm in agriculture which is our usecase).

**Comment by pengrad** [comment]
Released in `com.github.pengrad:mapscaleview:1.4.2`
