### ISSUE TITLE
Update release POM file

### ISSUE THREAD

**Issue by AlexanderEggers** [pengrad/MapScaleView#17]
I am using a license plugin for Android and noticed that this library does not offer any useful meta information regarding license, owner etc. Would it be possible if someone updates this via the current gradle config?

The current POM file only includes the name and version of this library.

Link to your current POM: https://bintray.com/pengrad/maven/download_file?file_path=com%2Fgithub%2Fpengrad%2Fmapscaleview%2F1.4.2%2Fmapscaleview-1.4.2.pom

**Comment by pengrad** [comment]
Hi, thanks!
Absolutely agree that we should have it.

Basically what we want is this inside the POM file?
```xml
  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>
```

**Comment by AlexanderEggers** [comment]
Yes, the license is important, the owner (therefore youf name?), a link to this repo and to the .git and maybe even the year when you published version x. Just an example what I did for one of my libs: https://github.com/Mordag/archtree/blob/develop/action/build.gradle I use two different .gradle files to build the POM and upload it to bintray (maybe that is going to help you as well?).

**Comment by pengrad** [comment]
Uploaded fixed POM
