### ISSUE TITLE
When tilt != 0

### ISSUE THREAD

**Issue by tujger** [pengrad/MapScaleView#2]
When tilt != 0 then MapScaleView shows very strange information - from 20 km to 2000 km...
Also, what about: 
- change properties dynamically 
(I know about Clark's fork but can't assign it to my build.gradle);
- showing scale in miles/kms

Thank you! :)

**Comment by pengrad** [comment]
Hi, i have plans to add support for dynamic properties and miles. Just need time. 
Also will check about tilt. 
Thanks!

**Comment by tujger** [comment]
Thank you! I'll wait :)

**Comment by pengrad** [comment]
I've fixed problems with tilt.
You can try it with this dependency 
`compile 'com.github.pengrad:MapScaleView:3d55f669b9'`

Will prepare other changes to 1.1 release

**Comment by tujger** [comment]
It works. Thank you! Andf happy New Year :)


>Суббота, 31 декабря 2016, 5:01 -05:00 от Stanislav Parshin <notifications@github.com>:
>
>I've fixed problems with tilt.
>You can try it with this dependency compile 'com.github.pengrad:MapScaleView:4ac51c2f73'
>Will prepare other changes to 1.1 release
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .



С уважением,
Edward.

**Comment by pengrad** [comment]
Released in 1.1.0

**Comment by tujger** [comment]
There are all fixed. Thank you!

**Comment by tujger** [comment]
Всех приветствую!

Хотелось бы познакомить Вас с ситуацией моей племянницы - http://savemenast.blogspot.it/

Спасибо!




С уважением,
Edward.

**Comment by tujger** [comment]
Добрый время суток,

Какой-то жулик от моего имени отправил просьбу подать денег. Врут все.



С уважением,
Edward.
