### ISSUE TITLE
Mapbox example

### ISSUE THREAD

**Issue by pengrad** [pengrad/MapScaleView#27]
Make activity with Mapbox map in sample app
Find the way how to restrict Mapbox token

**Comment by Haransis** [comment]
I can do that, but I'm not sure what you mean by "restrict Mapbox token"…
Do you want to prevent users from editing the Mapbox style ?

**Comment by pengrad** [comment]
Google maps key supports restriction, you can allow it to work only with specific app package and signing certificate.
https://developers.google.com/maps/api-key-best-practices#restrict_apikey

AFAIK, Mapbox doesn't support any of this.
So I suggest at least somehow encode it to make not available by automatic parsers.
For example we can split key string to 2 parts, encode them, put 1st in string val, 2nd in string.xml.
Then sample activity combine them and initiate mapbox

**Comment by Haransis** [comment]
Oh ok.
But this is just a sample app, not destined to production. 
Why not just hiding the token in a file which is in the .gitignore ? And say in the documentation that you need to place your own token to be able to test the app.
I feel like generating the token, encrypting and splitting it, is a lot for someone who just wants to test the sample.

**Comment by pengrad** [comment]
I want token to be stored in project, otherwise nobody will launch mapbox sample actually. 
That happened with google maps sample before.

> I feel like generating the token, encrypting and splitting it, is a lot for someone who just wants to test the sample.  

yes, definitely it is, thats why I want it to be already there, so someone just has to launch the activity.

basically it's a protection from robots parsing the GitHub looking for tokens.
but yeah, real person can open sample, modify the code and get the token.
I actually can do this with some apps using Mapbox, just grab the token in the apk.

so the token should be from the project without enabled billing in Mapbox account.

 maybe no need encryption, but at least not store it as is, split or base64 maybe

**Comment by Haransis** [comment]
Ok sure I get it.
