### ISSUE TITLE
Incorrect scaling?

### ISSUE THREAD

**Issue by ryust** [pengrad/MapScaleView#3]
I am not sure the scale is correct. See the attached screenshot showing a rural area in the US. The squares are generally roads a mile apart, but the MapScaleView is indicating the distance apart is 2 miles. Seems the scale is incorrectly reporting the distance (as seen in the upper left of the map).

![screenshot_20170428-113627](https://cloud.githubusercontent.com/assets/289010/25538260/9fd8999a-2c07-11e7-8677-be862b95e162.png)

**Comment by pengrad** [comment]
And how about google maps in this scale, they show correct? Just curious.

**Comment by ryust** [comment]
I'm using Android maps v2 which doesn't have a scale.

**Comment by pengrad** [comment]
I mean google maps app, if we approximate to about this level

**Comment by ryust** [comment]
Yes, it's correct there.

![screenshot_20170428-123136](https://cloud.githubusercontent.com/assets/289010/25539912/cdaa1770-2c0e-11e7-9efa-b554bbfb27b0.png)

**Comment by pengrad** [comment]
Thanks, will try to fix

**Comment by pengrad** [comment]
Please try 1.2.1 version, it should be ok now

**Comment by ryust** [comment]
Working perfectly in 1.2.1 now. Thanks!
