### ISSUE TITLE
Can not install, something wrong when sync gradle

### ISSUE THREAD

**Issue by barayuda** [pengrad/MapScaleView#4]
Hello, thanks anyway for your repo.

Can you help me? got this error 😢 

Error:(67, 13) Failed to resolve: com.github.pengrad:mapscaleview:1.2.1
<a href="openFile:/Users/barayuda/Documents/StudioProjects/MyMapp/build.gradle">Show in File</a><br>Show in Project Structure dialog

**Comment by barayuda** [comment]
This is my gradle

`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        if (rootProject.ext.has("gradle_classpath")) {
            classpath rootProject.ext.gradle_classpath
        } else {
            logger.warn('classpath not found in rootProject')
            classpath 'com.android.tools.build:gradle:2.3.2'
        }
    }
}

apply plugin: 'com.android.application'

android {

    if (rootProject.ext.has("compileSdkVersion")) {
        compileSdkVersion rootProject.ext.compileSdkVersion
        buildToolsVersion rootProject.ext.buildToolsVersion
    } else {
        logger.warn('compileSdkVersion not found in rootProject')
        compileSdkVersion 24
        buildToolsVersion "25.0.0"
    }

    defaultConfig {
        applicationId "de.j4velin.mapsmeasure"
        if (!project.file("key.properties").exists()) {
            resValue "string", "maps_api_key", "0000"
        }
    }

    signingConfigs {
        release
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            zipAlignEnabled true
            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
        }
        debug {
            signingConfig signingConfigs.release
            zipAlignEnabled true
            minifyEnabled false
            shrinkResources false
            debuggable true
        }
    }

    if (System.getenv("TRAVIS")) {
        lintOptions {
            ignoreWarnings true
            abortOnError false
        }
    }
}

dependencies {
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.google.android.gms:play-services-location:10.2.6'
    compile 'com.google.android.gms:play-services-maps:10.2.6'
    compile 'com.github.pengrad:mapscaleview:1.2.1'
}`

**Comment by pengrad** [comment]
Add `
repositories {  
   jcenter()  
}
` outside of `buildscript`.

Or maybe you enabled offline mode in android studio. 
Try `./gradlew` in terminal

**Comment by barayuda** [comment]
Thanks you,

solved by this:

allprojects {
    repositories {
        jcenter()
    }
}

---

Next, I found this error.
When implementing the code:
`05-19 19:47:50.286 15545-15545/com.barayuda.mapsmeasure E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.barayuda.mapsmeasure, PID: 15545
                                                                        java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.barayuda.mapsmeasure/com.barayuda.mapsmeasure.Map}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.Window.findViewById(int)' on a null object reference
                                                                         at Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.Window.findViewById(int)' on a null object reference
                                                                            at android.app.Activity.findViewById(Activity.java:2107)
                                                                            at com.barayuda.mapsmeasure.Map.<init>(Map.java:95)
`

and pointer refers to  MapScaleView scaleView = (MapScaleView) findViewById(R.id.scaleView);

I have put this code to my layout:
`<com.github.pengrad.mapscaleview.MapScaleView
            android:id="@+id/scaleView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|end"
            android:layout_margin="4dp"/>`

**Comment by pengrad** [comment]
Sorry, not connected to this lib
Check your class Map.java:95
