### ISSUE TITLE
Add feature auto scale_color

### ISSUE THREAD

**Issue by barayuda** [pengrad/MapScaleView#6]
Please add this feature auto scale color when map type change, like from satellite or road view.
Thank you

**Comment by pengrad** [comment]
Didn't get you

**Comment by barayuda** [comment]
I mean, color for scale_color can detect automatically after Google Map style.
Can we do it now?

**Comment by pengrad** [comment]
I've deleted play services as dependency, so we can do it by explicitly call method of MapScaleView.
Like `mapTypeChanged` with `MAP_TYPE_NORMAL, MAP_TYPE_NORMAL, ...` params.
Not automatically.

**Comment by barayuda** [comment]
I don't get it to using that, can you write some example to do that for clue? 
thank in advance

**Comment by pengrad** [comment]
Idea is it will be not automatically, you need to call method of ScaleView to tell that map type was changed and need to update color

**Comment by barayuda** [comment]
thank you, I will try it
