### ISSUE TITLE
add stroke color

### ISSUE THREAD

**Issue by iFr0z** [pengrad/MapScaleView#8]

**Comment by pengrad** [comment]
Stroke color can be changed via `setColor` together with text color.
You want to change color of strokes and text separately?

**Comment by iFr0z** [comment]
I want two color (white outline, black stroke) via google maps:

![capture](https://user-images.githubusercontent.com/4560636/33322797-08224a6e-d47d-11e7-9f91-02d9fd4382ba.PNG)

For night style map and light.

**Comment by pengrad** [comment]
Ok, try to implement it and send me pull request :)

**Comment by iFr0z** [comment]
ok, I'll try ;)

**Comment by webserveis** [comment]
I found this

https://stackoverflow.com/questions/1723846/how-do-you-draw-text-with-a-border-on-a-mapview-in-android

https://stackoverflow.com/a/3865861/3464919

**Comment by pengrad** [comment]
Released in 1.3.1

**Comment by iFr0z** [comment]
Big thx! :)
